apiVersion: v1
kind: Service
metadata:
  name: portfolio-app-service
spec:
  selector:
    io.foundation.application: portfolio
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-app-deployment
  labels:
    io.foundation.application: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.foundation.application: portfolio
  # Pod Template
  template:
    metadata:
      labels:
        io.foundation.application: portfolio
    spec:
      # Using local registry.
      containers:
        - name: portfolio-app-pod
          image: unreaalism/portfolio:latest
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: foundation-secrets
      imagePullSecrets:
        - name: foundation-registry
